In [1]:
#Import Libraries
import pandas as pd
import numpy as np
import joblib
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

# Data Splitting
from sklearn.model_selection import train_test_split

# Encoding
from sklearn.preprocessing import LabelEncoder

# Models
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier

# Evaluation
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

In [2]:
#Load Data
df = pd.read_csv("D:/Flight Delay Prediction/data/processed/flight_features.csv")

print("Dataset Shape:", df.shape)

df.head()

Dataset Shape: (528201, 29)

,flight_id,flight_date,marketing_airline_network,origin,dest,crs_dep_time,dep_delay,arr_delay,distance,crs_elapsed_time,...,is_weekend,departure_hour,departure_minute,departure_period,distance_category,flight_duration_minutes,flight_duration_hours,duration_category,delay_severity,flight_number
0,1,2025-01-15,DL,MSP,RDU,2026-07-12 12:50:00,-3,-14,980,149,...,0,12,50,Afternoon,Medium,149,2.48,Medium Flight,On Time,DL1001
1,2,2025-01-16,DL,MSP,RDU,2026-07-12 14:35:00,-4,-23,980,149,...,0,14,35,Afternoon,Medium,149,2.48,Medium Flight,On Time,DL1002
2,3,2025-01-17,DL,MSP,RDU,2026-07-12 14:35:00,-4,-14,980,149,...,0,14,35,Afternoon,Medium,149,2.48,Medium Flight,On Time,DL1003
3,4,2025-01-20,DL,MSP,RDU,2026-07-12 14:35:00,-2,15,980,149,...,0,14,35,Afternoon,Medium,149,2.48,Medium Flight,On Time,DL1004
4,5,2025-01-21,DL,MSP,RDU,2026-07-12 14:35:00,2,-10,980,149,...,0,14,35,Afternoon,Medium,149,2.48,Medium Flight,On Time,DL1005

In [5]:
#Feature Selection
drop_columns = [
    "flight_id",
    "flight_number",
    "flight_date",
    "arr_delay",
    "dep_delay",
    "month",
    "quarter",
    "flight_duration_hours",
    "delay_severity",
    "created_at",
    "crs_dep_time"
]

df = df.drop(columns=drop_columns)

df.head()

,marketing_airline_network,origin,dest,distance,crs_elapsed_time,cancelled,diverted,delay_status,day,day_name,day_of_week,is_weekend,departure_hour,departure_minute,departure_period,distance_category,flight_duration_minutes,duration_category
0,DL,MSP,RDU,980,149,False,False,0,15,Wednesday,2,0,12,50,Afternoon,Medium,149,Medium Flight
1,DL,MSP,RDU,980,149,False,False,0,16,Thursday,3,0,14,35,Afternoon,Medium,149,Medium Flight
2,DL,MSP,RDU,980,149,False,False,0,17,Friday,4,0,14,35,Afternoon,Medium,149,Medium Flight
3,DL,MSP,RDU,980,149,False,False,0,20,Monday,0,0,14,35,Afternoon,Medium,149,Medium Flight
4,DL,MSP,RDU,980,149,False,False,0,21,Tuesday,1,0,14,35,Afternoon,Medium,149,Medium Flight

In [6]:
#Feature and Target
X = df.drop(columns=["delay_status"])

y = df["delay_status"]

print("Features Shape :", X.shape)
print("Target Shape :", y.shape)

Features Shape : (528201, 17)
Target Shape : (528201,)

In [7]:
categorical_features = [
    "marketing_airline_network",
    "origin",
    "dest",
    "day_name",
    "departure_period",
    "distance_category",
    "duration_category"
]

numerical_features = [
    "distance",
    "crs_elapsed_time",
    "day",
    "day_of_week",
    "is_weekend",
    "departure_hour",
    "departure_minute",
    "flight_duration_minutes"
]

In [8]:
preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            StandardScaler(),
            numerical_features
        ),

        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        )
    ]
)

In [9]:
#Train-Test Data
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)


print("Training Size :", X_train.shape)
print("Testing Size :", X_test.shape)

Training Size : (422560, 17)
Testing Size : (105641, 17)

In [10]:
#Class Distribution
print(y_train.value_counts(normalize=True) * 100)

delay_status
0    89.436293
1    10.563707
Name: proportion, dtype: float64

In [11]:
#Columns used for training
print("Features Used for Training:")
print(X.columns.tolist())

Features Used for Training:
['marketing_airline_network', 'origin', 'dest', 'distance', 'crs_elapsed_time', 'cancelled', 'diverted', 'day', 'day_name', 'day_of_week', 'is_weekend', 'departure_hour', 'departure_minute', 'departure_period', 'distance_category', 'flight_duration_minutes', 'duration_category']

In [12]:
# Logistic Regression Model

logistic_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),

        (
            "classifier",

            LogisticRegression(
                class_weight="balanced",
                random_state=42,
                max_iter=3000
            )
        )
    ]
)

In [13]:
#Train
logistic_pipeline.fit(
    X_train,
    y_train
)

C:\Users\Dhruv Mittal\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_logistic.py:451: OptimizeWarning: Unknown solver options: iprint
  opt_res = optimize.minimize(

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['distance',
                                                   'crs_elapsed_time', 'day',
                                                   'day_of_week', 'is_weekend',
                                                   'departure_hour',
                                                   'departure_minute',
                                                   'flight_duration_minutes']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['marketing_airline_network',
                                                   'origin', 'dest', 'day_name',
                                                   'departure_period',
                                                   'distance_category',
                                                   'duration_category'])])),
                ('classifier',
                 LogisticRegression(class_weight='balanced', max_iter=3000,
                                    random_state=42))])

In [14]:
#Predict
y_pred_lr = logistic_pipeline.predict(X_test)

#Probability
y_prob_lr = logistic_pipeline.predict_proba(X_test)

lr_accuracy = accuracy_score(y_test, y_pred_lr)
lr_precision = precision_score(y_test, y_pred_lr)
lr_recall = recall_score(y_test, y_pred_lr)
lr_f1 = f1_score(y_test, y_pred_lr)

print(f"Accuracy : {lr_accuracy:.4f}")
print(f"Precision: {lr_precision:.4f}")
print(f"Recall   : {lr_recall:.4f}")
print(f"F1 Score : {lr_f1:.4f}")

Accuracy : 0.5900
Precision: 0.1483
Recall   : 0.6074
F1 Score : 0.2384

In [15]:
print(confusion_matrix(y_test, y_pred_lr))

[[55548 38934]
 [ 4381  6778]]

In [16]:
print(classification_report(y_test, y_pred_lr))

              precision    recall  f1-score   support

           0       0.93      0.59      0.72     94482
           1       0.15      0.61      0.24     11159

    accuracy                           0.59    105641
   macro avg       0.54      0.60      0.48    105641
weighted avg       0.84      0.59      0.67    105641

In [17]:
lr_results = {
    "Model":"Logistic Regression",
    "Accuracy":lr_accuracy,
    "Precision":lr_precision,
    "Recall":lr_recall,
    "F1 Score":lr_f1
}

In [18]:
#Decision Tree
decision_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),

        (
            "classifier",

            DecisionTreeClassifier(
                class_weight="balanced",
                random_state=42,
                max_depth=15
            )
        )
    ]
)

In [19]:
#Train
decision_pipeline.fit(
    X_train,
    y_train
)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['distance',
                                                   'crs_elapsed_time', 'day',
                                                   'day_of_week', 'is_weekend',
                                                   'departure_hour',
                                                   'departure_minute',
                                                   'flight_duration_minutes']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['marketing_airline_network',
                                                   'origin', 'dest', 'day_name',
                                                   'departure_period',
                                                   'distance_category',
                                                   'duration_category'])])),
                ('classifier',
                 DecisionTreeClassifier(class_weight='balanced', max_depth=15,
                                        random_state=42))])

In [20]:
#Predict
y_pred_dt = decision_pipeline.predict(X_test)

#Probability
y_prob_dt = decision_pipeline.predict_proba(X_test)

dt_accuracy = accuracy_score(y_test, y_pred_dt)
dt_precision = precision_score(y_test, y_pred_dt)
dt_recall = recall_score(y_test, y_pred_dt)
dt_f1 = f1_score(y_test, y_pred_dt)

print(f"Accuracy : {dt_accuracy:.4f}")
print(f"Precision: {dt_precision:.4f}")
print(f"Recall   : {dt_recall:.4f}")
print(f"F1 Score : {dt_f1:.4f}")

Accuracy : 0.6720
Precision: 0.1750
Recall   : 0.5667
F1 Score : 0.2674

In [21]:
print(confusion_matrix(y_test, y_pred_dt))

[[64668 29814]
 [ 4835  6324]]

In [22]:
print(classification_report(y_test, y_pred_dt))

              precision    recall  f1-score   support

           0       0.93      0.68      0.79     94482
           1       0.17      0.57      0.27     11159

    accuracy                           0.67    105641
   macro avg       0.55      0.63      0.53    105641
weighted avg       0.85      0.67      0.73    105641

In [23]:
dt_results = {
    "Model":"Decision Tree",
    "Accuracy":dt_accuracy,
    "Precision":dt_precision,
    "Recall":dt_recall,
    "F1 Score":dt_f1
}

In [24]:
#Random Forest
random_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),

        ("classifier",
         RandomForestClassifier(
             n_estimators=300,
             max_depth=20,
             min_samples_split=5,
             min_samples_leaf=2,
             class_weight="balanced_subsample",
             random_state=42,
             n_jobs=-1
         ))
    ]
)

In [25]:
#Train
random_pipeline.fit(
    X_train,
    y_train
)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['distance',
                                                   'crs_elapsed_time', 'day',
                                                   'day_of_week', 'is_weekend',
                                                   'departure_hour',
                                                   'departure_minute',
                                                   'flight_duration_minutes']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['marketing_airline_network',
                                                   'origin', 'dest', 'day_name',
                                                   'departure_period',
                                                   'distance_category',
                                                   'duration_category'])])),
                ('classifier',
                 RandomForestClassifier(class_weight='balanced_subsample',
                                        max_depth=20, min_samples_leaf=2,
                                        min_samples_split=5, n_estimators=300,
                                        n_jobs=-1, random_state=42))])

In [26]:
#Predict
y_pred_rf = random_pipeline.predict(X_test)
# print(pd.Series(y_pred_rf).value_counts())
# print(y_test.value_counts())
#Probability
y_prob_rf = random_pipeline.predict_proba(X_test)
# print(confusion_matrix(y_test, y_pred_rf))

rf_accuracy = accuracy_score(y_test, y_pred_rf)
rf_precision = precision_score(y_test, y_pred_rf)
rf_recall = recall_score(y_test, y_pred_rf)
rf_f1 = f1_score(y_test, y_pred_rf)

print(f"Accuracy : {rf_accuracy:.4f}")
print(f"Precision: {rf_precision:.4f}")
print(f"Recall   : {rf_recall:.4f}")
print(f"F1 Score : {rf_f1:.4f}")

Accuracy : 0.7101
Precision: 0.1844
Recall   : 0.5097
F1 Score : 0.2708

In [27]:
print(confusion_matrix(y_test, y_pred_rf))

[[69324 25158]
 [ 5471  5688]]

In [28]:
print(classification_report(y_test, y_pred_rf))

              precision    recall  f1-score   support

           0       0.93      0.73      0.82     94482
           1       0.18      0.51      0.27     11159

    accuracy                           0.71    105641
   macro avg       0.56      0.62      0.54    105641
weighted avg       0.85      0.71      0.76    105641

In [31]:
rf_results = {
    "Model":"Random Forest",
    "Accuracy":rf_accuracy,
    "Precision":rf_precision,
    "Recall":rf_recall,
    "F1 Score":rf_f1
}

In [ ]:
#Gradient Boosting
gradient_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),

        (
            "classifier",

            GradientBoostingClassifier(
                random_state=42
            )
        )
    ]
)

In [ ]:
#Train
gradient_pipeline.fit(
    X_train,
    y_train
)

In [ ]:
#Predict
y_pred_gb = gradient_pipeline.predict(X_test)

#Probability
y_prob_gb = gradient_pipeline.predict_proba(X_test)

gb_accuracy = accuracy_score(y_test, y_pred_gb)
gb_precision = precision_score(y_test, y_pred_gb)
gb_recall = recall_score(y_test, y_pred_gb)
gb_f1 = f1_score(y_test, y_pred_gb)

print(f"Accuracy : {gb_accuracy:.4f}")
print(f"Precision: {gb_precision:.4f}")
print(f"Recall   : {gb_recall:.4f}")
print(f"F1 Score : {gb_f1:.4f}")

In [ ]:
print(confusion_matrix(y_test, y_pred_gb))

In [ ]:
print(classification_report(y_test, y_pred_gb))

In [ ]:
gb_results = {
    "Model":"Gradient Boosting",
    "Accuracy":gb_accuracy,
    "Precision":gb_precision,
    "Recall":gb_recall,
    "F1 Score":gb_f1
}

In [ ]:
results = pd.DataFrame([
    lr_results,
    dt_results,
    rf_results,
    gb_results
])

results

In [32]:
#Save Pipeline

import joblib

joblib.dump(
    random_pipeline,
    r"D:\Flight Delay Prediction\src\models\flight_delay_pipeline.pkl",
    compress=5
)

print("✅ Flight Delay Pipeline Saved Successfully!")

✅ Flight Delay Pipeline Saved Successfully!

In [ ]:

print(X_train.columns.tolist())

In [ ]:
import sklearn
print(sklearn.__version__)